#Use the official Python image from Docker hub
FROM python:3.10-slim

#Set the working directory
WORKDIR /app

#Copy the current directory contents into the container at /app
COPY . /app

#Install any needed packages which were specified in requirements.txt
RUN pip install flask

#Make port 5000 available to world outside of the container
EXPOSE 5000

#Run app.py when the container launches
CMD ["python", "app.py"]